export const CURRENT_RESTAURANT = 'CURRENT_RESTAURANT';
export const ORDERLIST_CHANGED = 'ORDERLIST_CHANGED';
export const RESET_CART = 'RESET_CART';
export const SET_CART_DISPLAY = 'SET_CART_DISPLAY';
export const ORDER_PLACED = 'ORDER_PLACED';
